apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix.fullname" . }}-synapse-saml-keys
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.synapse.saml.tls_cert | b64enc }}
  tls.key: {{ .Values.synapse.saml.tls_key  | b64enc }}
