apiVersion: v2
name: matrix
description: A Helm chart to deploy a Matrix homeserver stack into Kubernetes
icon: "https://dacruz21.github.io/helm-charts/icons/matrix.svg"
home: "https://github.com/dacruz21/matrix-chart"
sources:
  - "https://github.com/dacruz21/matrix-chart"

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 2.13.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.135.2

maintainers:
  - name: "Eddie"
    email: "eddie@oblak.be"
    url: "https://github.com/oblak-be"

dependencies:
  - name: postgresql
    version: 17.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
